/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc_program;

import jdbc_model.Mahasiswa;
import jdbc_service.MysqlMahasiswaService;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author haritspermana
 */
public class JFrameUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameUtama.class.getName());
    private final MysqlMahasiswaService service = new MysqlMahasiswaService();

    private final DefaultListModel<String> modelId = new DefaultListModel<>();
    private final DefaultListModel<String> modelNama = new DefaultListModel<>();

    private boolean sinkronPilihan = false;

    /**
     * Creates new form JFrameUtama
     */
    public JFrameUtama() {
        initComponents();
        konfigurasiAwal();
    }
    
private void konfigurasiAwal() {
    ls_id.setModel(modelId);
    ls_nama.setModel(modelNama);

    tf_namaHapus.setEditable(false);

    ls_id.addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            pilihData(ls_id.getSelectedIndex());
        }
    });

    ls_nama.addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            pilihData(ls_nama.getSelectedIndex());
        }
    });

    addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            service.closeConnection();
        }
    });
}

private void refreshData() {
    modelId.clear();
    modelNama.clear();

    List<Mahasiswa> data = service.getAll();

    for (Mahasiswa mhs : data) {
        modelId.addElement(String.valueOf(mhs.getId()));
        modelNama.addElement(mhs.getNama());
    }
}

private void pilihData(int index) {
    if (sinkronPilihan) {
        return;
    }

    if (index < 0 || index >= modelId.getSize()) {
        return;
    }

    sinkronPilihan = true;
    ls_id.setSelectedIndex(index);
    ls_nama.setSelectedIndex(index);
    sinkronPilihan = false;

    String id = modelId.getElementAt(index);
    String nama = modelNama.getElementAt(index);

    tf_noEdit.setText(id);
    tf_namaEdit.setText(nama);

    tf_noHapus.setText(id);
    tf_namaHapus.setText(nama);
}

private int buatIdBaru() {
    int maxId = 0;

    List<Mahasiswa> data = service.getAll();

    for (Mahasiswa mhs : data) {
        if (mhs.getId() > maxId) {
            maxId = mhs.getId();
        }
    }

    return maxId + 1;
}

private Integer ambilId(String teks) {
    try {
        return Integer.parseInt(teks.trim());
    } catch (NumberFormatException nfe) {
        JOptionPane.showMessageDialog(
                this,
                "ID harus berupa angka.",
                "Input salah",
                JOptionPane.WARNING_MESSAGE
        );
        return null;
    }
}

private void isiEditDariId() {
    Integer id = ambilId(tf_noEdit.getText());

    if (id == null) {
        return;
    }

    Mahasiswa mhs = service.getById(id);

    if (mhs == null) {
        JOptionPane.showMessageDialog(this, "Data dengan ID " + id + " tidak ditemukan.");
        return;
    }

    tf_namaEdit.setText(mhs.getNama());
}

private void isiHapusDariId() {
    Integer id = ambilId(tf_noHapus.getText());

    if (id == null) {
        return;
    }

    Mahasiswa mhs = service.getById(id);

    if (mhs == null) {
        JOptionPane.showMessageDialog(this, "Data dengan ID " + id + " tidak ditemukan.");
        return;
    }

    tf_namaHapus.setText(mhs.getNama());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ls_id = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ls_nama = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        btn_AmbilSemuaData = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        btn_Tambahkan = new javax.swing.JButton();
        tf_noEdit = new javax.swing.JTextField();
        tf_namaEdit = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        tf_noHapus = new javax.swing.JTextField();
        tf_namaHapus = new javax.swing.JTextField();
        btn_hapus = new javax.swing.JButton();
        btn_ResetIndeks = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("NAMA");

        ls_id.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ls_id);

        ls_nama.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ls_nama);

        jLabel3.setText("KELOLA DATA MAHASISWA");

        btn_AmbilSemuaData.setText("Ambil Semua Data");
        btn_AmbilSemuaData.addActionListener(this::btn_AmbilSemuaDataActionPerformed);

        jLabel4.setText("nama :");

        tf_nama.addActionListener(this::tf_namaActionPerformed);

        btn_Tambahkan.setText("Tambahkan");
        btn_Tambahkan.addActionListener(this::btn_TambahkanActionPerformed);

        tf_noEdit.addActionListener(this::tf_noEditActionPerformed);

        tf_namaEdit.addActionListener(this::tf_namaEditActionPerformed);

        btn_edit.setText("Edit");
        btn_edit.addActionListener(this::btn_editActionPerformed);

        tf_noHapus.addActionListener(this::tf_noHapusActionPerformed);

        tf_namaHapus.addActionListener(this::tf_namaHapusActionPerformed);

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(this::btn_hapusActionPerformed);

        btn_ResetIndeks.setText("Reset indeks");
        btn_ResetIndeks.addActionListener(this::btn_ResetIndeksActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(btn_AmbilSemuaData))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(tf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Tambahkan)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tf_noEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_namaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_edit))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tf_noHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_namaHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_hapus))
                                    .addComponent(btn_ResetIndeks))))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_AmbilSemuaData)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Tambahkan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_noEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_namaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_edit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_noHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_namaHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_hapus))
                        .addGap(18, 18, 18)
                        .addComponent(btn_ResetIndeks))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TambahkanActionPerformed
        // TODO add your handling code here:
        String nama = tf_nama.getText().trim();

        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong.");
            tf_nama.requestFocus();
            return;
        }

        int idBaru = buatIdBaru();

        Mahasiswa mhs = new Mahasiswa(idBaru, nama);
        service.add(mhs);

        tf_nama.setText("");
        tf_noHapus.setText("");
        tf_namaHapus.setText("");
        tf_noEdit.setText("");
        tf_namaEdit.setText("");
        refreshData();
    }//GEN-LAST:event_btn_TambahkanActionPerformed

    private void tf_noEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_noEditActionPerformed
        // TODO add your handling code here:
        isiEditDariId();
    }//GEN-LAST:event_tf_noEditActionPerformed

    private void tf_noHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_noHapusActionPerformed
        // TODO add your handling code here:
        isiHapusDariId();
    }//GEN-LAST:event_tf_noHapusActionPerformed

    private void tf_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_namaActionPerformed
        // TODO add your handling code here:
        btn_TambahkanActionPerformed(evt);
    }//GEN-LAST:event_tf_namaActionPerformed

    private void btn_AmbilSemuaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AmbilSemuaDataActionPerformed
        // TODO add your handling code here:
        refreshData();
    }//GEN-LAST:event_btn_AmbilSemuaDataActionPerformed

    private void tf_namaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_namaEditActionPerformed
        // TODO add your handling code here:
        btn_editActionPerformed(evt);
    }//GEN-LAST:event_tf_namaEditActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        Integer id = ambilId(tf_noEdit.getText());

        if (id == null) {
            return;
        }

        String namaBaru = tf_namaEdit.getText().trim();

        if (namaBaru.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama edit tidak boleh kosong.");
            tf_namaEdit.requestFocus();
            return;
        }

        Mahasiswa cek = service.getById(id);

       if (cek == null) {
           JOptionPane.showMessageDialog(this, "Data dengan ID " + id + " tidak ditemukan.");
           return;
        }

        Mahasiswa mhs = new Mahasiswa(id, namaBaru);
        service.update(mhs);

        tf_noEdit.setText("");
        tf_namaEdit.setText("");
        tf_noHapus.setText("");
        tf_namaHapus.setText("");
        tf_nama.setText("");

        refreshData();
    }//GEN-LAST:event_btn_editActionPerformed

    private void tf_namaHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_namaHapusActionPerformed
        // TODO add your handling code here:
        btn_hapusActionPerformed(evt);
    }//GEN-LAST:event_tf_namaHapusActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        Integer id = ambilId(tf_noHapus.getText());

        if (id == null) {
            return;
        }

        Mahasiswa mhs = service.getById(id);

        if (mhs == null) {
            JOptionPane.showMessageDialog(this, "Data dengan ID " + id + " tidak ditemukan.");
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin menghapus data?\nID: " + mhs.getId() + "\nNama: " + mhs.getNama(),
                "Konfirmasi hapus",
                JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {
            service.delete(id);

            tf_noHapus.setText("");
            tf_namaHapus.setText("");
            tf_noEdit.setText("");
            tf_namaEdit.setText("");
            tf_nama.setText("");

            refreshData();
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_ResetIndeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetIndeksActionPerformed
        // TODO add your handling code here:
        if (!service.isEmpty()) {
            int konfirmasi = JOptionPane.showConfirmDialog(
                    this,
                    "Reset AUTO_INCREMENT biasanya efektif jika tabel kosong.\nTetap lanjutkan?",
                    "Konfirmasi reset indeks",
                    JOptionPane.YES_NO_OPTION
            );

            if (konfirmasi != JOptionPane.YES_OPTION) {
                return;
            }
        }

        service.indexReset();
        refreshData();
    }//GEN-LAST:event_btn_ResetIndeksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AmbilSemuaData;
    private javax.swing.JButton btn_ResetIndeks;
    private javax.swing.JButton btn_Tambahkan;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> ls_id;
    private javax.swing.JList<String> ls_nama;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_namaEdit;
    private javax.swing.JTextField tf_namaHapus;
    private javax.swing.JTextField tf_noEdit;
    private javax.swing.JTextField tf_noHapus;
    // End of variables declaration//GEN-END:variables
}
