/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyek4;

import javax.swing.DefaultListModel;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 *
 * @author haritspermana
 */
public class GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());
    DefaultListModel<String> dlm;
 
    List<String>        itemList = new ArrayList<>();
    Set<String>         itemSet  = new LinkedHashSet<>();
    Map<String, String> itemMap  = new LinkedHashMap<>();   
    
    String[] datasAwal = {"buku", "meja", "kursi", "tas", "pintu"};
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        // Inisialisasi DefaultListModel dan pasang ke jList
        dlm = new DefaultListModel<>();
        list.setModel(dlm);
 
        // Isi jList dengan data awal
        for (String data : datasAwal) {
            dlm.addElement(data);
        }
 
        // Tampilkan jumlah data tersimpan awal (semuanya 0)
        updateLabels();
    }
    
    private void updateLabels() {
        label_List.setText("Data tersimpan = " + itemList.size());
        label_Set .setText("Data tersimpan = " + itemSet.size());
        label_Map .setText("Data tersimpan = " + itemMap.size());
    }
    
    private void addItem(String namaItem) {
        if (namaItem == null || namaItem.trim().isEmpty()) return;
        dlm.addElement(namaItem.trim());
    }

    @SuppressWarnings("unchecked")

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        btn_ClearAll = new javax.swing.JButton();
        btn_SaveToList = new javax.swing.JButton();
        label_List = new javax.swing.JLabel();
        btn_InsertDataList = new javax.swing.JButton();
        btn_SaveToSet = new javax.swing.JButton();
        btn_InsertDataSet = new javax.swing.JButton();
        btn_SaveToMap = new javax.swing.JButton();
        btn_InsertDataMap = new javax.swing.JButton();
        label_Set = new javax.swing.JLabel();
        label_Map = new javax.swing.JLabel();
        label_ItemName = new javax.swing.JLabel();
        TextField = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list);

        btn_ClearAll.setText("Clear All");
        btn_ClearAll.addActionListener(this::btn_ClearAllActionPerformed);

        btn_SaveToList.setText("Save to List");
        btn_SaveToList.addActionListener(this::btn_SaveToListActionPerformed);

        label_List.setText("Data tersimpan = ");

        btn_InsertDataList.setText("Insert data List");
        btn_InsertDataList.addActionListener(this::btn_InsertDataListActionPerformed);

        btn_SaveToSet.setText("Save to Set");
        btn_SaveToSet.addActionListener(this::btn_SaveToSetActionPerformed);

        btn_InsertDataSet.setText("Insert data Set");
        btn_InsertDataSet.addActionListener(this::btn_InsertDataSetActionPerformed);

        btn_SaveToMap.setText("Save to Map");
        btn_SaveToMap.addActionListener(this::btn_SaveToMapActionPerformed);

        btn_InsertDataMap.setText("insert data Map");
        btn_InsertDataMap.addActionListener(this::btn_InsertDataMapActionPerformed);

        label_Set.setText("Data tersimpan =");

        label_Map.setText("Data tersimpan =");

        label_ItemName.setText("Item Name:");

        TextField.addActionListener(this::TextFieldActionPerformed);

        btn_add.setText("add");
        btn_add.addActionListener(this::btn_addActionPerformed);

        btn_update.setText("update");
        btn_update.addActionListener(this::btn_updateActionPerformed);

        btn_delete.setText("delete");
        btn_delete.addActionListener(this::btn_deleteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(btn_ClearAll, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_InsertDataList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_SaveToSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_InsertDataSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_SaveToMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_InsertDataMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_SaveToList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(label_ItemName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_List)
                            .addComponent(label_Set)
                            .addComponent(label_Map)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_update)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_SaveToList)
                            .addComponent(label_List))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_InsertDataList)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_SaveToSet)
                            .addComponent(label_Set))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_InsertDataSet)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_SaveToMap)
                            .addComponent(label_Map))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_InsertDataMap)
                        .addGap(32, 32, 32)
                        .addComponent(label_ItemName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_update)
                    .addComponent(btn_delete)
                    .addComponent(btn_ClearAll))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InsertDataListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertDataListActionPerformed
        // TODO add your handling code here:
        dlm.clear();
        for (String item : itemList) {
            dlm.addElement(item);
        }
    }//GEN-LAST:event_btn_InsertDataListActionPerformed

    private void btn_SaveToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveToListActionPerformed
        // TODO add your handling code here:
        if (!itemList.isEmpty()) {
            itemList.clear();
        }
        for (int i = 0; i < dlm.getSize(); i++) {
            itemList.add(dlm.getElementAt(i));
        }
        updateLabels();
    }//GEN-LAST:event_btn_SaveToListActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        addItem(TextField.getText());
        TextField.setText("");

    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        int index = list.getSelectedIndex();
        if (index < 0) return;          // tidak ada yang dipilih, abaikan
        dlm.removeElementAt(index);
        TextField.setText("");
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_ClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearAllActionPerformed
        // TODO add your handling code here:
        dlm.clear();
        TextField.setText("");
    }//GEN-LAST:event_btn_ClearAllActionPerformed

    private void btn_SaveToSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveToSetActionPerformed
        // TODO add your handling code here:
        itemSet.clear();
        for (int i = 0; i < dlm.getSize(); i++) {
            itemSet.add(dlm.getElementAt(i));
        }
        updateLabels();
    }//GEN-LAST:event_btn_SaveToSetActionPerformed

    private void btn_InsertDataSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertDataSetActionPerformed
        // TODO add your handling code here:
        dlm.clear();
        for (String item : itemSet) {
            dlm.addElement(item);
        }
    }//GEN-LAST:event_btn_InsertDataSetActionPerformed

    private void btn_SaveToMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveToMapActionPerformed
        // TODO add your handling code here:
        itemMap.clear();
        for (int i = 0; i < dlm.getSize(); i++) {
            itemMap.put(String.valueOf(i), dlm.getElementAt(i));
        }
        updateLabels();
    }//GEN-LAST:event_btn_SaveToMapActionPerformed

    private void btn_InsertDataMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertDataMapActionPerformed
        // TODO add your handling code here:
        dlm.clear();
        for (int i = 0; i < itemMap.size(); i++) {
            dlm.addElement(itemMap.get(String.valueOf(i)));
        }
    }//GEN-LAST:event_btn_InsertDataMapActionPerformed

    private void TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldActionPerformed
        // TODO add your handling code here:
        addItem(TextField.getText());
        TextField.setText("");
    }//GEN-LAST:event_TextFieldActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        int index = list.getSelectedIndex();
        if (index < 0) return;                          // tidak ada yang dipilih
        String newValue = TextField.getText().trim();
        if (newValue.isEmpty()) return;                 // TextField kosong, abaikan
        dlm.setElementAt(newValue, index);
        TextField.setText("");
    }//GEN-LAST:event_btn_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField;
    private javax.swing.JButton btn_ClearAll;
    private javax.swing.JButton btn_InsertDataList;
    private javax.swing.JButton btn_InsertDataMap;
    private javax.swing.JButton btn_InsertDataSet;
    private javax.swing.JButton btn_SaveToList;
    private javax.swing.JButton btn_SaveToMap;
    private javax.swing.JButton btn_SaveToSet;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_ItemName;
    private javax.swing.JLabel label_List;
    private javax.swing.JLabel label_Map;
    private javax.swing.JLabel label_Set;
    private javax.swing.JList<String> list;
    // End of variables declaration//GEN-END:variables
}
